language: python

python:
- '3.6'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex

script: "python3 ./travis/build.py"

after_success:
- "python3 ./travis/publish.py"

env:
  global:
  - secure: AlBOGiHnkOAzTXYDkUOjKm6zYsms5qSDQ+UBB2pYE+d0rOXdnkBU0PwU/tEKys8wcpyTr5QNWruR8pu612pwyMSWWX63YpTSultZ7NboEzhpWLLVbmYIqozLbw/0t1oMwn48gO0AHuP+V2hWRVM9RPQW0uyH6j0lF5PPdDjybUtypbuJHIo9fjGUCuH5Ke3rcO9esXBq/q9D5/jCSN5Jm8blsdRVQhKLnCxfxAnXFp4lV7v3L/TKUe1MG7vHSrUjIShAzc0kkY3NV/NlKSX4W9Vah0FXfTj5vVQ70CmhW8hfX8tGPB40IQyuz3aPy5BjxzI+ZovPo26g9nlmZO8/eK6SM5MO5Fn/eDCG6d2+GQOAUhj1I39pBsdCjLTl6QGFyQDrW19DUWVzHx2NTXJj4cHP5t1ahme2HaIHaBylTnq6FotI+JqiIoQEbQJpKwNiBxxQYiXkFYfCOMCKgwx7bmhMeY/H1eAgkH5srX+5Ry+lmyKqfmUsTlyvgNTttsmwzBu3Qg5d6DZjXy7J8lgcaCwF8IPXjVCzQQtJNsZIxUvxLmY/VFqBbZI+HK8ojQ1cwmo2xPw41ae/AZ85bRAdtfVCZpPlQsnSzzd4/UHYyV4TVm7MS0YSt/SIETmACiycp35ao8q8BcUzw+Vubpl/GfHGP7Fwxq+ufumgzAdDoVo=
  - GH_USER_NAME: sourabh2311
  - GH_PROJECT_NAME: MuftEducationPdfs
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/docs/courses.pdf
